<?php
return [
    [ 'huruf' => 'A', 'gambar' => 'A.jpg', 'penjelasan' => 'Kepalkan tangan, semua jari menutup, ibu jari berada di samping telunjuk.' ],
    [ 'huruf' => 'B', 'gambar' => 'B.jpg', 'penjelasan' => 'Telapak tangan terbuka menghadap depan, jari-jari rapat dan lurus, ibu jari menekuk ke telapak.' ],
    [ 'huruf' => 'C', 'gambar' => 'C.jpg', 'penjelasan' => 'Bentuk tangan seperti huruf C dengan jari-jari melengkung.' ],
    [ 'huruf' => 'D', 'gambar' => 'D.jpg', 'penjelasan' => 'Ujung ibu jari dan jari tengah bertemu membentuk lingkaran, jari telunjuk lurus ke atas.' ],
    [ 'huruf' => 'E', 'gambar' => 'E.jpg', 'penjelasan' => 'Semua jari ditekuk ke arah telapak hingga membentuk kepalan longgar.' ],
    [ 'huruf' => 'F', 'gambar' => 'F.jpg', 'penjelasan' => 'Ibu jari dan telunjuk bertemu membentuk lingkaran, jari lainnya lurus ke atas.' ],
    [ 'huruf' => 'G', 'gambar' => 'G.jpg', 'penjelasan' => 'Jari telunjuk dan ibu jari lurus ke samping, jari lainnya ditekuk.' ],
    [ 'huruf' => 'H', 'gambar' => 'H.jpg', 'penjelasan' => 'Jari telunjuk dan tengah lurus sejajar ke samping, jari lainnya ditekuk.' ],
    [ 'huruf' => 'I', 'gambar' => 'I.jpg', 'penjelasan' => 'Kepalkan tangan dengan jari kelingking lurus ke atas.' ],
    [ 'huruf' => 'J', 'gambar' => 'J.png', 'penjelasan' => 'Seperti huruf I, namun jari kelingking digerakkan membentuk huruf J.' ],
    [ 'huruf' => 'K', 'gambar' => 'K.jpg', 'penjelasan' => 'Jari telunjuk dan tengah membentuk huruf V, ibu jari berada di antara keduanya.' ],
    [ 'huruf' => 'L', 'gambar' => 'L.jpg', 'penjelasan' => 'Jari telunjuk lurus ke atas dan ibu jari lurus ke samping membentuk sudut L.' ],
    [ 'huruf' => 'M', 'gambar' => 'M.jpg', 'penjelasan' => 'Ibu jari berada di bawah tiga jari (telunjuk, tengah, manis), kelingking menutup.' ],
    [ 'huruf' => 'N', 'gambar' => 'N.jpg', 'penjelasan' => 'Ibu jari berada di bawah dua jari (telunjuk dan tengah), jari lainnya menutup.' ],
    [ 'huruf' => 'O', 'gambar' => 'O.jpg', 'penjelasan' => 'Semua jari melengkung dan bertemu membentuk lingkaran.' ],
    [ 'huruf' => 'P', 'gambar' => 'P.jpg', 'penjelasan' => 'Mirip huruf K, namun posisi jari mengarah ke bawah.' ],
    [ 'huruf' => 'Q', 'gambar' => 'Q.jpg', 'penjelasan' => 'Mirip huruf G, namun posisi tangan mengarah ke bawah.' ],
    [ 'huruf' => 'R', 'gambar' => 'R.jpg', 'penjelasan' => 'Jari telunjuk dan tengah menyilang, jari lainnya ditekuk.' ],
    [ 'huruf' => 'S', 'gambar' => 'S.jpg', 'penjelasan' => 'Kepalkan tangan, ibu jari berada di depan jari-jari.' ],
    [ 'huruf' => 'T', 'gambar' => 'T.jpg', 'penjelasan' => 'Ibu jari berada di antara jari telunjuk dan jari tengah yang menutup.' ],
    [ 'huruf' => 'U', 'gambar' => 'U.jpg', 'penjelasan' => 'Jari telunjuk dan tengah lurus dan rapat ke atas, jari lainnya menutup.' ],
    [ 'huruf' => 'V', 'gambar' => 'V.jpg', 'penjelasan' => 'Jari telunjuk dan tengah lurus membentuk huruf V.' ],
    [ 'huruf' => 'W', 'gambar' => 'W.jpg', 'penjelasan' => 'Jari telunjuk, tengah, dan manis lurus ke atas.' ],
    [ 'huruf' => 'X', 'gambar' => 'X.jpg', 'penjelasan' => 'Jari telunjuk ditekuk membentuk kait, jari lainnya menutup.' ],
    [ 'huruf' => 'Y', 'gambar' => 'Y.jpg', 'penjelasan' => 'Ibu jari dan kelingking lurus, jari lainnya menutup.' ],
    [ 'huruf' => 'Z', 'gambar' => 'Z.png', 'penjelasan' => 'Jari telunjuk lurus dan digerakkan membentuk huruf Z di udara.' ],
];

